'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PictureBook.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desserts() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desserts", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desserts_icecream_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desserts_icecream_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desserts_pastry_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desserts_pastry_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property desserts_sundae_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desserts_sundae_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_animals_bear_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_animals_bear_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_animals_fox() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_animals_fox", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_animals_fox_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_animals_fox_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_animals_owl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_animals_owl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property forest_animals_owl_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("forest_animals_owl_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fruits() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fruits", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fruits_apple_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fruits_apple_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fruits_lemon_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fruits_lemon_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fruits_watermelon_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fruits_watermelon_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property garden_of_Eden() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("garden_of_Eden", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property intro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("intro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle_animals_elephant() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle_animals_elephant", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle_animals_elephant_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle_animals_elephant_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle_animals_monkey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle_animals_monkey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle_animals_monkey_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle_animals_monkey_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle_animals_parrot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle_animals_parrot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property jungle_animals_parrot_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("jungle_animals_parrot_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains_animals_caribou() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains_animals_caribou", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains_animals_caribou_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains_animals_caribou_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains_animals_eagle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains_animals_eagle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains_animals_eagle_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains_animals_eagle_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains_animals_wolf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains_animals_wolf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountains_animals_wolf_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountains_animals_wolf_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property noahs_ark() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noahs_ark", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean_animals_hermit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean_animals_hermit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean_animals_hermit_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean_animals_hermit_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean_animals_octopus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean_animals_octopus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean_animals_octopus_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean_animals_octopus_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean_animals_penguins() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean_animals_penguins", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ocean_animals_penguins_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean_animals_penguins_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property simple_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("simple_background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vegetables_carrot_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vegetables_carrot_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vegetables_potato_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vegetables_potato_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property vegetables_tomato_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vegetables_tomato_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property veggies() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("veggies", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
